### ISSUE TITLE
Unable to reference verse:0

### ISSUE THREAD

**Issue by yurividal** [bitfocus/companion-module-opensong#1]
Hi @NoahCallaway, thanks for this amazing module. I have tested it, and it seems that the only function that i am unable to use is `/presentation/song/current/verse/verse:0`
The variable does not allow value 0. 
We currently use Verse 0 to display our copyright info for each song. Any chance you can allow 0 in the "Opensong: Current Song Verse" action?

**Comment by yurividal** [comment]
Fixed by [this PR](https://github.com/bitfocus/companion-module-opensong/pull/2). Feel free to merge .

**Comment by yurividal** [comment]
![image](https://user-images.githubusercontent.com/8555749/103089786-ffb86000-45e6-11eb-850f-3c51b27e14d2.png)

**Comment by NoahCallaway** [comment]
Done! Hadn't crossed my mind you might need a verse 0.
